### ISSUE TITLE
EssentialsX & TacoSpigot

### ISSUE THREAD

**Issue by NoopyyGaming** [TacoSpigot/TacoSpigot#106]
Dear Developers of TacoSpigot,

i'm opening this issue to request you to make  TacoSpigot compatible with EssentialsX Because i really want to use this jar server on my server before opening. It could be great if you do that :)

Best Regards

**Comment by MrExplode** [comment]
If you wouldn't noticed, this project looks dead, since the last commit were made more more than a year ago.

**Comment by LoXR** [comment]
Looks like EssentialsX made a compatibility fix not too long ago either way.
