### ISSUE TITLE
Possibility of getting the CI site back up?

### ISSUE THREAD

**Issue by TylerNRobertson** [TacoSpigot/TacoSpigot#107]
Its impossible to build the project currently without the website.

**Comment by Keurig-Creator** [comment]
The jar itself does not run.

**Comment by Pakistaniboy442** [comment]
Yeah Help If You Have Your DNS SERVER set TO 1.1.1.1 CHANGE TO GOOGLES

**Comment by Keurig-Creator** [comment]
What?

**Comment by TylerNRobertson** [comment]
@Pakistaniboy442 no idea what your talking about

**Comment by Keurig-Creator** [comment]
Is it possible to fix the jar from not starting? The jar worked a few months ago and now it does not.

**Comment by Pakistaniboy442** [comment]
> @Pakistaniboy442 no idea what your talking about

Umm apparently that was not me...
