### ISSUE TITLE
Build Server

### ISSUE THREAD

**Issue by MCTyler** [TacoSpigot/TacoSpigot#11]
I can't get this to Build and the Build Server is Down so I can't Download the Latest Version. Help Please!

**Comment by Techcable** [comment]
Fixed.
Sorry for the downtime.

**Comment by MCTyler** [comment]
I used a Git PowerShell to run ./build.sh but it can't create any directories and when I run it as Admin it won't run sh ./build.sh. Guess I need to read more. Thanks!

**Comment by Techcable** [comment]
You don't need to build it from source. We use paperclip so you can download from the CI.

**Comment by MCTyler** [comment]
Ok, I was just curious and wanted to build it...just a hobby/wannabe.
