### ISSUE TITLE
Server packet spamming crash

### ISSUE THREAD

**Issue by HunterGPlays** [TacoSpigot/TacoSpigot#12]
![TacoSpigot ver](http://i.imgur.com/86kowpe.png)
I run Waterfall too.

Some guy logged on my server and before I know it, I was offline. No, not connection-wise but my server had crashed. I don't even know where to look. I think it's to do with packet spamming since Orebfuscator reported it but I don't know at all.

Logs and stack trace: http://pastebin.com/216YpMSD

**Comment by Techcable** [comment]
You should probably get a plugin to throttle dig packets.

**Comment by Techcable** [comment]
The log expired, is this still occuring?

**Comment by HunterGPlays** [comment]
My server is offline because I have my final exams approaching, so I haven't been able to test it

**Comment by Techcable** [comment]
I'll reopen when you give me the logs again ;)
