### ISSUE TITLE
anyway of getting latest build via wget?

### ISSUE THREAD

**Issue by Twi5TeD** [TacoSpigot/TacoSpigot#13]
anyway of getting latest build via wget? i would like to use this so i can get the latest build via a press of a button :)

**Comment by Techcable** [comment]
Oh my, you can't since the jars have the build number in them :o

**Comment by Twi5TeD** [comment]
oh ok i thought you could since ive seen others have it like bungee waterfall

**Comment by HunterGPlays** [comment]
You technically can if you download the latest successful build zip, run something to extract it and copy *.jar over. I've done this for someone's startup script.

-----Original Message-----

**Comment by Techcable** [comment]
Should be fixed for latest builds.
We now build to "TacoSpigot.jar".
Respond if this doesn't work correctly.
