### ISSUE TITLE
Server start, and stopp error [Windows]

### ISSUE THREAD

**Issue by andris155** [TacoSpigot/TacoSpigot#17]
Start
![kepkivagas3](https://cloud.githubusercontent.com/assets/8324198/14056314/abdbab62-f2ea-11e5-9d0f-42d81279db3e.PNG)
Stop
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/14056315/ae5520d0-f2ea-11e5-8ece-e8f373863368.PNG)

**Comment by Techcable** [comment]
Duplicate of #25.
