### ISSUE TITLE
Version check error

### ISSUE THREAD

**Issue by andris155** [TacoSpigot/TacoSpigot#18]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/14061726/940b644e-f387-11e5-899a-48e2485aa94c.PNG)

**Comment by Techcable** [comment]
Is there an error in the log?

**Comment by andris155** [comment]
"Error obtaining version information"

**Comment by Techcable** [comment]
Should be fixed in recent builds. Respond/complain if not
