### ISSUE TITLE
TacoSpigot 1.9 World Border Glitch (Latest 1.9 Build from Jenkins)

### ISSUE THREAD

**Issue by EliteXSkill** [TacoSpigot/TacoSpigot#20]
Using latest TacoSpigot 1.9 build.
Using the latest dev/availible build for all of my following plugins:
NoCheatPlus, CoreProtect, GroupManager, ClearLag, Vault, WorldGuard, ChestCommands, EssentialsGeoIP, EssentialsChat, EssentialsSpawn, WorldEdit, Essentials, and CombatTagPlus (disabled)

   When setting worldborder, world border glitches out. Accidentally set world border to 1 x 1 and then readjusted, but did not fix. When ever gamemode 0, player suffocates immediately in a wall. Combated dying by changing buffer and damage, but still can not interact with blocks. Whenever I try to adjust worldborder, it never shows up. Adjusted center to 0.0 and made 900000 to attempt to fix, but still hasn't worked. No errors in console whatsoever. Seems like WorldBorder is simply not adjusting, but still gives me a chat confirmation that it is.

**Comment by EliteXSkill** [comment]
Confirmed feature FIXED in Paper's latest 1.9 build; assuming issue is limited to TacoSpigot's code only.

**Comment by Techcable** [comment]
I've updated to latest paper, does it still occur in build #31?

**Comment by EliteXSkill** [comment]
Issue seems to be resolved.
Thanks for the quick fix C:.
