### ISSUE TITLE
TacoSpigot 1.9 Frost Walker Glitch (Latest 1.9 Build from Jenkins)

### ISSUE THREAD

**Issue by EliteXSkill** [TacoSpigot/TacoSpigot#21]
Ola,
Using the latest Build 37 you released yesterday, Frost Walker enchant doesn't work on water. Attempted in Survival, Creative, and Adventure. On some cheaper PCs (like laptops), it even crashed their computers. Could you check this out and release a fix if possible?

**Comment by phase** [comment]
It crashes their _entire computer_, or just Minecraft?

**Comment by EliteXSkill** [comment]
Minecraft.

**Comment by Techcable** [comment]
What is a frost walker?

**Comment by EliteXSkill** [comment]
Frost Walker is one of the new enchants added in 1.9., where it puts ice under you when you walk on water. The 2 clients who's Minecraft crashed arn't here right now, so I'll give you the error when I see them.

**Comment by Techcable** [comment]
Does this still occur in the latest [1.9.2 pre-release](https://github.com/TacoSpigot/TacoSpigot/releases/tag/v1.9.2-R0.1)?

**Comment by Techcable** [comment]
Insufficient information
