### ISSUE TITLE
Hopper/Chunk-Tick lag

### ISSUE THREAD

**Issue by jordanwilliams1** [TacoSpigot/TacoSpigot#24]
Can you maybe looking into optimizing hoppers and Chunk Ticks?

I Can just about hold 30 people, I Haven't notice a different at all between paper, Spigot and Taco, I Get the same timings :( 

http://timings.aikar.co/v2/?id=e6378dc5a66c45b993b58813f12eedb7&section=all

**Comment by jordanwilliams1** [comment]
^^ CPU: I7 4790K

**Comment by Techcable** [comment]
What version are you on?

**Comment by jordanwilliams1** [comment]
Build #43

https://ci.techcable.net/job/TacoSpigot/

**Comment by Techcable** [comment]
Can I have a worldguard profile?
Run `/wg profile -p -t *`

**Comment by jordanwilliams1** [comment]
Sorry I'm not using taco anymore, This bug is still in paper and it lags the crap out of my server:

https://github.com/PaperMC/Paper/issues/138

**Comment by Nickshelton80** [comment]
Mine isn't as bad as some of the above, but I too am getting way more entities than normal spigot:

WG Report:
http://pastebin.com/e81qT5TF

I have animals limited to 7 and set to spawn every 800 ticks and they are still extremely high.

**Comment by mibby** [comment]
@Techcable Any plans on porting over the hopper patches to Paper anytime soon? Been getting reports of low TPS readings on my server and found out someone has an area with 10k hoppers in use. All the tile entity ticking is dropping my performance :(
