### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mat41997** [TacoSpigot/TacoSpigot#27]
logs
http://hastebin.com/benukanome.avrasm

**Comment by RoboMWM** [comment]
Second stack trace is extremely likely to be plugin-caused - most likely FastCraft+ or some other plugin that uses inventories. https://github.com/BenWoodworth/FastCraftPlus/issues/20

**Comment by Techcable** [comment]
Does this still occur in the [1.9.2 pre release](https://github.com/TacoSpigot/TacoSpigot/releases/tag/v1.9.2-R0.1)?

**Comment by Techcable** [comment]
For some reason github didn't close this even though e1014f18b71c4173c1e044a28a34f49a563b8cd6 fixes it
