### ISSUE TITLE
(Windows) Startup error, no color in console

### ISSUE THREAD

**Issue by MClausz** [TacoSpigot/TacoSpigot#37]
I get this error everytime I starts the server
http://pastebin.com/W9fBPx1M
And the console don't have color when the server running, and it's difficult to type commands in the console.
I've tried everything, like installing Visual C++ 2008 (x86) or 2010 (x64)
TacoSpigot build #61
This issue doesn't happen in other spigot or paperspigot builds.

**Comment by Techcable** [comment]
Duplicate of #25
