### ISSUE TITLE
Player can't crafting item

### ISSUE THREAD

**Issue by SotrForgotten** [TacoSpigot/TacoSpigot#38]
Player can't crafting item, so I just set hopper.fire-InventoryMoveItemEvent to 'false' in taco.yml (default is 'true')
and restart server, but can't crafting item still,

(Sorry for bad english :/)

TacoSpigot version: v1.9.4-R0.1-af15657
(no crash)

**Comment by Techcable** [comment]
Fixed in the latest 1.10 build.
