### ISSUE TITLE
[1.10.2] b#79 - Bugged pistons

### ISSUE THREAD

**Issue by L4BORG** [TacoSpigot/TacoSpigot#43]
Pistons will turn into drops when activated.

How? Place piston on the floor, place lever next to piston, trigger lever - piston will extend and block will disappear (there will be piston dropped...) and there will be extended piston head.

**Comment by sgdc3** [comment]
Have you tried without plugins?

**Comment by Techcable** [comment]
Does it happen on Paper?

**Comment by Techcable** [comment]
Duplicate of PaperMC/Paper#352
