### ISSUE TITLE
Sword damage is ridiculously nerfed

### ISSUE THREAD

**Issue by PsychoLynx** [TacoSpigot/TacoSpigot#44]
Hi! Using TacoSpigot build 81, mob battles have become impossible since all swords/axes seem to cap damage at 2hp (or one heart). Latest Paper (b810) doesn't have this issue so I believe its exclusive to Taco.

**Comment by Techcable** [comment]
What is your taco.yml?

**Comment by PsychoLynx** [comment]
config-version: 1
betterPvp: false
disableDataWatcherReadLocking: false
useArraysForBlockStates: false
useArraysForDatawatcher: false
world-settings:
  default:
    verbose: true
    armor-stand:
      optimize-movement: false
    hopper:
      fire-InventoryMoveItemEvent: true
      push-based: true

**Comment by melinstagibson** [comment]
set betterpvp to true....

**Comment by Techcable** [comment]
yeah, I think I see the bug, its a missed diff in the betterPvp patch.
I need to add some obfhelpers I guess

**Comment by PsychoLynx** [comment]
Thanks you for solving this!
