### ISSUE TITLE
[1.8.8] ProtocolSupport incompatibility

### ISSUE THREAD

**Issue by Bonista** [TacoSpigot/TacoSpigot#49]
http://pastebin.com/Tk7xZpLf

Is this something I have to fix with ProtocolSupport or is it TacoSpigot's issue?

If it is something I have to fix, I would appreciate your help in directing me to the right route.

**Comment by Bonista** [comment]
I found out where the problem lies.

https://github.com/PaperMC/Paper/commit/4c7641d1919222fdf02903bc529af1d6cbbe6146

Time to clone the repo and fix it ;-;

**Comment by Bonista** [comment]
I did  changed Short.MAX_VALUE to  Short.MAX_VALUE * 10, which is a terrible fix for it.

What would other people do?

**Comment by Techcable** [comment]
I'm not sure you can legitimately receive a packet longer than Short.MAX_BYTES, so it could be that somebody's trying to attack you. Is it you having this issue, or one of your players?

**Comment by Bonista** [comment]
@Techable unfortunately its all 1.7 players

**Comment by Bonista** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/blob/master/src/protocolsupport/protocol/serializer/ProtocolSupportPacketDataSerializer.java (Current version (1.10))

https://github.com/ProtocolSupport/ProtocolSupport/blob/29d9ba0476029bf976487d0653acdf135fd345b4/src/protocolsupport/protocol/PacketDataSerializer.java (The version that works with 1.8.8)

I believe this is where it's supposed to be fixed, and TacoSpigot shouldn't be touched. What do you suggest doing?

**Comment by SnakeDaoust1232** [comment]
I need this fix as well. It only does this with tacospigot. I can use paperspigot 1.8.8 and spigot 1.8.8 fine.

Error: http://pastebin.com/g7xSH5Lb
Version: Newest

**Comment by CheatSupport** [comment]
Any updates? I would love this. 

@SnakeDaoust1232 did you get it to work?

**Comment by SnakeDaoust1232** [comment]
Yes. The link on yives mirror was the issue. Download the correct version off of tacospigot's official GitHub.

**Comment by CheatSupport** [comment]
@SnakeDaoust1232 for taco spigot? Also can you like me protocolsupport you have, it would be very appreciated.

**Comment by CheatSupport** [comment]
@SnakeDaoust1232 please link me your protocolsupport.jar file?

**Comment by SnakeDaoust1232** [comment]
@Bonista I would like your tacospigot jar that you got working. Are you available?
