### ISSUE TITLE
What's happening?

### ISSUE THREAD

**Issue by jordanwilliams1** [TacoSpigot/TacoSpigot#50]
Is taco still getting updates? I Couldn't find a 1.10 update version. Does paper have all the taco optimizations for hoppers? I Read taco can reduce hopper lag by 90% and my hoppers are taking up 35% of my server load (on normal spigot)

**Comment by Techcable** [comment]
[TacoSpigot](https://is.gd/TacoSpigot) is fully updated to 1.10, and is [available on the jenkins](https://ci.techcable.net/job/TacoSpigot/).

**Comment by BestMark** [comment]
How often will you update TacoSpigot in the future?

**Comment by Techcable** [comment]
Yes, I'll be continuing to update TacoSpigot.
I'll update it to 1.11 as soon as Paper releases.
