### ISSUE TITLE
[1.8.8] Issues with compatibility with ProtocolSupport for 1.7 players 

### ISSUE THREAD

**Issue by Buzznacker** [TacoSpigot/TacoSpigot#51]
It seems like everytime I log into the server on a 1.7 client I get this error: http://badwa.re/i/E2BfQzV.png
I'm currently using TacoSpigot 1.8.8 with only 1 modifications in the entityhuman class so I doubt that would be a problem, I'm currently running ProtocolSupport v.4.22.1 if anyone has a fix for this it would be really appreciated if you could share it.

**Comment by Buzznacker** [comment]
Nvm Found the issue and fixed it

**Comment by CheatSupport** [comment]
@Buzznacker Please dm on twitter @DreamRaids or contact me, I need this
