### ISSUE TITLE
1.11.2 update?

### ISSUE THREAD

**Issue by Zilacon** [TacoSpigot/TacoSpigot#53]
So uh, whens 1.11.2 going to be a thing?

**Comment by evernife** [comment]
waiting 2

**Comment by sgdc3** [comment]
same :/

**Comment by PsychoLynx** [comment]
Me three (or four)

**Comment by Zilacon** [comment]
Now we need a new release :)

**Comment by Techcable** [comment]
It's [build 87 on the CI](https://ci.techcable.net/job/TacoSpigot/87/)

**Comment by Zilacon** [comment]
Thanks.

**Comment by evernife** [comment]
Thanks.
