### ISSUE TITLE
Server Lag | Cant figure it out. Jar related?

### ISSUE THREAD

**Issue by SnakeDaoust1232** [TacoSpigot/TacoSpigot#55]
Here is my situation. My server starts to lag when I enter a area that has like 3k spawners placed down. They aren't spawning any mobs, they are just placed down.

Here is a 1 minute timings report of me "not" in the area with the spawners. (No Lag)
- https://timings.aikar.co/?id=73e0ac4214494307843b6e7e8824aabc

Here is a 1 minute timings report of me "in" the area with the spawners. (Lag)
- https://timings.aikar.co/?id=96cfcd5aa52d4947bb1f2ceded4785c5

HUGE DIFFERENCE

I run tacospigot 1.8 which is a fork of paperspigot basically.
- TacoSpigot: https://github.com/TacoSpigot/TacoSpigot

Video of the situation: https://www.youtube.com/watch?v=M6nm8ZTuGAw&feature=youtu.be

**Comment by Techcable** [comment]
This is not a bug, and I can't do much about the lag.
Try changing `mob-spawner-tick-rate` in your paper.yml

**Comment by SnakeDaoust1232** [comment]
I set the tick rate down to 1 and its still causing lag. Maybe you could make it so that if there are more than 100 spawners directly connected to eachother, in a certain amount of chunks, it disable all the spawners and their mechanics.

**Comment by Techcable** [comment]
You could either write a plugin to do that, or just remove all those spawners.

**Comment by SnakeDaoust1232** [comment]
Thank you for your time. Im going to see if i can get a dev to make it.
