### ISSUE TITLE
[1.8.8] Can't interact with blocks without /op

### ISSUE THREAD

**Issue by yeahspvp** [TacoSpigot/TacoSpigot#56]
http://prntscr.com/enx0fj is what I get in console when I try to open a chest without op. This only happens when I use TacoSpigot 1.8.8, other spigots work. I know it isn't a plugin because I'm not using any in the errors screenshot. 

Only when you're /op'd, you can open chests, use anvils, etc.

**Comment by Techcable** [comment]
What plugins do you have installed?
Just because there aren't any errors from them, doesn't mean they aren't causing the issue.

Can you reproduce this without any plugins installed?

**Comment by yeahspvp** [comment]
No, I wasn't using any plugins, even with plugins the same thing happens.
No, the world was generated by EmptyWorldGenerator while I was using the 1.8.8 TacoSpigot.
I no longer have the log, but there were no errors or warnings. The only "WARNS" were: http://prntscr.com/enx0fj

**Comment by Techcable** [comment]
Again, could you please [gist](https://gist.github.com/

**Comment by yeahspvp** [comment]
https://gist.github.com/yeahspvp/6365272671fa4401b2c267c7a407057c

**Comment by Techcable** [comment]
Try setting `spawn-protection=0` in the server.properties file.

**Comment by yeahspvp** [comment]
Setting the spawn protection to 0 worked! Thanks a lot!

**Comment by Techcable** [comment]
You're welcome :wink;
