### ISSUE TITLE
Paperspigot Compat

### ISSUE THREAD

**Issue by SnakeDaoust1232** [TacoSpigot/TacoSpigot#63]
1.8 tacospigot isn't compatible with via version at all. Please add support, I'll pay

**Comment by Techcable** [comment]
How is it incompatible? It already should work fine if it works on regular 1.8.8.

**Comment by SnakeDaoust1232** [comment]
@Techcable I was mistaken. The issue i am having is with protocol support. Its not allowing 1.7 clients to play. I have tried every version of TacoSpigot 1.8.8 on the build server and none of hem work with protocolsupport and 1.7 clients. I have contacted you via email and on AquiferMC. I'm willing to pay to get this fixed. Its kicking them with this message:

SnakeDaoust lost connection: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.handler.codec.DecoderException: The received a byte array longer than allowed 61696 > 32767

Same Bug: https://github.com/TacoSpigot/TacoSpigot/issues/49

**Comment by GitCoords** [comment]
@SnakeDaoust1232 This is caused by a security patch added by Paper. I can remove the patch for you if you want and send you a custom build. PM me on Spigot: @BeastSpencer (not sure if this is allowed here)

**Comment by SnakeDaoust1232** [comment]
@GitCoords I would like to see what @Techcable has to say first. But why was the security patch added?

**Comment by Techcable** [comment]
It prevents clients from sending packets that are too big, which apparently is possible on 1.7. I'll  go modify the security patch to allow large packets from 1.17 clients when ProtocolSupport is installed.

**Comment by SnakeDaoust1232** [comment]
Thank you! OMG.

**Comment by SnakeDaoust1232** [comment]
@Techcable Are you going to add it to the build server or am i going to have to compile it all myself? I've tried compiling it before and it says im missing "TacoSpigot-Server" and "TacoSpigot-API". So i cant compile anything. I would love it if you could add it to the build server.

**Comment by Techcable** [comment]
I'll push it to the build server once I get around to fixing it 😉 
I might push some other long awaited fixes too, like the one for the blockstate arrays.

**Comment by SnakeDaoust1232** [comment]
Awesome. I cant wait. Thanks!

**Comment by SnakeDaoust1232** [comment]
@Techcable I'm not trying to be whatever but when can we expect the updated version? I understand you are probably busy but maybe a guess as to when you are going to get the free time to fix it?

**Comment by Techcable** [comment]
It's been finals week, so I've been really busy. Hopefully, I'll get time to fix it over the weekend.

**Comment by SnakeDaoust1232** [comment]
Ok. Thanks for the update

**Comment by SnakeDaoust1232** [comment]
@Techcable Finals done yet? :(

**Comment by Techcable** [comment]
Just reopen this issue and comment below if that commit doesn't fix it.

**Comment by SnakeDaoust1232** [comment]
@Techcable One thing: https://gyazo.com/e53576259d4d86c9a2cc839062820d93

**Comment by Techcable** [comment]
Try regular `TacoSpigot.jar` instead of `TacoSpigot-24.jar`

**Comment by SnakeDaoust1232** [comment]
@Techcable It worked but now its not compatible with viaversion. I made an issue on viaversion but they are being arrogant. Here: https://github.com/MylesIsCool/ViaVersion/issues/682

**Comment by SnakeDaoust1232** [comment]
@Techcable I cant re-open the issue since you were the one who closed it.

**Comment by SnakeDaoust1232** [comment]
@Techcable You there?

**Comment by Techcable** [comment]
Please open a new issue, and [gist](gist.github.com) your logs instead of screenshotting them. Fixing this issue while maintaining compatibility with ViaVersion will require some atrocious​ compatibility hacks that I'm not exactly sure how to implement. Hopefully netty has some way to set custom channel attributes 😬
