### ISSUE TITLE
Incompatibility with ViaVersion's custom PacketDecoder.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [TacoSpigot/TacoSpigot#64]
When I try to login to the server i get these errors.
Console: https://gyazo.com/c69a88b17888ea1bf5119433205639ce
Client: https://gyazo.com/363ca9606bd7f8a8408980e603c3355f

**Comment by SnakeDaoust1232** [comment]
@Techcable Can you not view the gyazo screenshots? I don't know why i need to put them in a gist.

**Comment by Techcable** [comment]
I can access the screenshot fine, It's just difficult to read. Believe it or not this is a ViaVersion compatibility issue as they hijack the server's networking system and my fix doesn't seem to like it.

**Comment by SnakeDaoust1232** [comment]
What should i do from here. Contact the guys at viaversion? Or are you taking care of it?

**Comment by Techcable** [comment]
It's something I need to take care of, and I intend to reimplement the patch more cleanly by using netty channel attributes.

**Comment by SnakeDaoust1232** [comment]
Ok, sounds good

**Comment by CheatSupport** [comment]
@Techcable thank you, please try and do this soon I donated not so long ago remember! :) I love your work.

**Comment by Techcable** [comment]
Fixed as of 2778432865668967642c3415ed81fdd74b79ea70 and build 25.

**Comment by SnakeDaoust1232** [comment]
Didn't work :(

1.7.10 Client

Console Error: https://hastebin.com/acolaqumun.css
In Game Message:  https://gyazo.com/1006b925a66ee7afeb07f1669f887dfd

**Comment by SnakeDaoust1232** [comment]
@Techcable It kicks me within like 5 seconds. Maybe the chunks loading?

**Comment by SnakeDaoust1232** [comment]
@pschichtel Hi. For some reason, im unable to join the server on anything above a 1.8 client. Im using the most updated viaversion. I think your blocking it in the jar.2

**Comment by Techcable** [comment]
I'm doing no such thing. Make sure it's not a ViaVersion issue since it's their responsibility to support new versions.

**Comment by SnakeDaoust1232** [comment]
Okay. Im just making sure you werent blocking it for some reason. Ill go make an issue on viaversions github. Thank you for getting it to this point. I have one more question.

Would it be beneificial to use tacospigot on all my servers for performace. I only thought i needed it for my factions server but a friend said that there are many optimizations that help with supporting more players and such.

**Comment by Techcable** [comment]
It could help, and is definitely safer than PaperSpigot for 1.8.8.

**Comment by SnakeDaoust1232** [comment]
@Techcable This wouldnt cause this issue right? https://gyazo.com/419efaa79a57b6962b23bfd902cbcf27

**Comment by Techcable** [comment]
It shouldn't cause that issue.

**Comment by SnakeDaoust1232** [comment]
Something is going on here. I contacted viaversion and hexacord and they both turned me down. For some reason tacospigot 1.8.8 is blocking 1.9 clients from joining. Normal spigot and paper spigot work fine, but taco spigot is blocking it. Tacospigot is not compatible with hexcord, which is what i use for bungee. https://github.com/HexagonMC/BungeeCord/issues/163. Could you please look into why paper works, and tacospigot doesnt?

**Comment by SnakeDaoust1232** [comment]
@Techcable  Just to let you know, for anyone else that may have my issue as well... i had latebind set to true, it needs to be set to false. Then everything works fine.
