### ISSUE TITLE
My Taco.yml doesn't have many options to configure like Armorstand movement and stuff

### ISSUE THREAD

**Issue by Fonzee9** [TacoSpigot/TacoSpigot#71]
Is this really all the optimizations Taco gives over paper? There used to be so many now theirs 5 and the armor stand movement one seems to be removed

https://pastebin.com/r1eqLi5m

**Comment by Fonzee9** [comment]
Also i reset my config twice and its the same with no armourstand movement thing so its default config?

**Comment by Techcable** [comment]
What's your version?

**Comment by Fonzee9** [comment]
1.12 Build 105

**Comment by Tiippex** [comment]
I have the same problem
This server is running Paper version git-TacoSpigot-"b23f17ef" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 Previous version: git-Paper-1427 (MC: 1.12.2)

**Comment by Techcable** [comment]
I removed my option because now a plugin can do it through Paper's new API. I guess I should probably re-add the option, although it's still a niche feature.

**Comment by Tiippex** [comment]
Can you link the plugin please? :o

**Comment by Techcable** [comment]
A plugin _can_ do it, although I'm not sure if there's one that actually does.

**Comment by Tiippex** [comment]
Can you send me a short message when its done?
I really need the armorstand improvement...

**Comment by Techcable** [comment]
@Tiippex 
It's done. I've released an [armor stand freeze plugin](https://github.com/TacoSpigot/ArmorStandFreeze) which does the exact same thing as the old option but works as a plugin instead.
This is now the 'official' alternative to this old option and you can grab a binary from [the release page](https://github.com/TacoSpigot/ArmorStandFreeze/releases).
There are no options, no commands, just drop it and go.
