### ISSUE TITLE
Unknown Erros? - Benni R.

### ISSUE THREAD

**Issue by Ventix** [TacoSpigot/TacoSpigot#84]
Hello, 
The following error:
https://hastebin.com/biwizakoca.md

My LobbyCountDown:105:
```java
   private void randomTeleport() {
        int count = 1;
        for (Player alive : Bukkit.getOnlinePlayers()) {
            if (Main.getInstance().getDataProvider().getAlivePlayers.contains(alive.getUniqueId().toString())) {
                alive.teleport(Main.getInstance().getLocationProvider().getLocation("Spawn" + count, "spawns.yml"));
                count++;
            }
        }
    }
```

` WorldCreator.name("WL3").createWorld();` == Load the world in onenable

Dear, 
benni!!!!!

**Comment by Ventix** [comment]
#push!!!

**Comment by electronicboy** [comment]
you're teleporting a player async.

**Comment by Ventix** [comment]
i dont teleport players async? lol

**Comment by Ventix** [comment]
i dont teleport players async? lol

**Comment by electronicboy** [comment]
I'd suggest reading your own stack trace properly, your call to the teleport method is clearly happening from the async thread pool.

**Comment by Ventix** [comment]
how its work?

**Comment by Techcable** [comment]
This issue is a plugin issue, and asynchronous teleportation will never be supported.
`at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)`
Learn how to code properly, and read your own stack traces.
This is not a TacoSpigot issue, and never will be.
