### ISSUE TITLE
Taco.yml

### ISSUE THREAD

**Issue by MCTyler** [TacoSpigot/TacoSpigot#9]
Is this right?
`# This is the main configuration file for TacoSpigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to TacoSpigot,
# join us at the IRC.
# 
# IRC: #taco @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=taco )

config-version: 1
world-settings:
  default:
    verbose: true
    hopper:
      fire-InventoryMoveItemEvent: true
      push-based: true
    armor-stand:
      optimize-movement: false
`

**Comment by MCTyler** [comment]
I don't really call that Tons.....

**Comment by Techcable** [comment]
Yes it is, you should also configure 'paper.yml'.

**Comment by MCTyler** [comment]
Ok...I wasn't sure if I had to copy Paper.yml over  to this one or just edit it...
