### ISSUE TITLE
Sand issues

### ISSUE THREAD

**Issue by voodootje0** [TacoSpigot/TacoSpigot#90]
We are having an issue with TacoSpigot 1.8.8, sometimes when people are using sand stackers, the sand will glitch and will not act how it should. 

This is a video:
https://www.youtube.com/watch?v=X_2NyIoiLwE&feature=youtu.be

If there is need for more information let me know.

**Comment by Gonsda** [comment]
To my knowledge this has nothing to do with Taco, happens on Paper jars as well.
