### ISSUE TITLE
[QUESTION] Tacospigot 1.8.8 version features 

### ISSUE THREAD

**Issue by Alexre** [TacoSpigot/TacoSpigot#95]
Hi!

I just want to ask you if the latest builds of taco 1.8.8 contains the new feautres on the config of paper like min-chunk-load-threads and other ones that have been added in 1.12+ versions.

Thanks!

**Comment by Techcable** [comment]
1.8.8 does not have the new features from 1.12+ Paper versions.
I will not be backporting features now or any time in the foreseeable future.
