### ISSUE TITLE
TacoSpigot-Server and TacoSpigot-API missing for version/1.8.8

### ISSUE THREAD

**Issue by Tyiee** [TacoSpigot/TacoSpigot#97]
Not sure whats going on here, but when i build it sends this message...
![error](https://user-images.githubusercontent.com/46653243/57589684-edfa7580-74f3-11e9-99af-3175fd0ccfde.PNG)

**Comment by Pr0methean** [comment]
I get the same error building against both b6f44bb0 and f8ba67d6.
